EXTRA_ARGS=$@

INSTALL_DIR=$PWD/../install
TRILINOS_HOME=/home/sdhammo/git/trilinos-github-repo

rm CMakeCache.txt
rm -fr CMakeFiles

COMPILE_FLAGS=""

cmake \
-D BUILD_SHARED_LIBS:BOOL=OFF \
-D TPL_ENABLE_DLlib:BOOL=OFF \
-D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
-D Trilinos_ENABLE_EXAMPLES:BOOL=OFF \
-D Trilinos_ENABLE_TESTS:BOOL=OFF \
-D Trilinos_ENABLE_DEBUG=OFF \
-D Trilinos_ENABLE_ALL_PACKAGES:BOOL=OFF \
-D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF \
-D Trilinos_ENABLE_Shards:BOOL=ON \
-D Trilinos_ENABLE_Intrepid:BOOL=ON \
-D Trilinos_ENABLE_Teuchos:BOOL=ON \
-D Trilinos_ENABLE_KokkosAlgorithms:BOOL=ON \
-D Trilinos_ENABLE_KokkosCore:BOOL=ON \
-D Trilinos_ENABLE_KokkosContainers:BOOL=ON \
-D Trilinos_ENABLE_KokkosAlgorithms:BOOL=ON \
-D Trilinos_ENABLE_OpenMP:BOOL=ON \
-D Kokkos_ENABLE_Pthread:BOOL=OFF \
-D Kokkos_ENABLE_OpenMP:BOOL=ON \
-D Kokkos_ENABLE_Serial:BOOL=ON \
-D TPL_ENABLE_HWLOC:BOOL=OFF \
-D Kokkos_ENABLE_HWLOC:BOOL=OFF \
-D Trilinos_ENABLE_Tpetra:BOOL=ON \
-D Tpetra_INST_SERIAL:BOOL=ON \
-D Tpetra_INST_OPENMP:BOOL=ON \
-D Tpetra_ENABLE_Kokkos_Refactor:BOOL=ON \
-D Tpetra_INST_INT_LONG:BOOL=ON \
-D KOKKOS_ARCH="HSW" \
\
-D Trilinos_ENABLE_SEACAS:BOOL=OFF \
-D Trilinos_ENABLE_SEACASIoss:BOOL=OFF \
-D TPL_ENABLE_Netcdf:BOOL=OFF \
-D TPL_ENABLE_HDF5:BOOL=OFF \
-D Tpetra_INST_COMPLEX_FLOAT:BOOL=OFF \
-D Tpetra_INST_COMPLEX_DOUBLE:BOOL=OFF \
\
-D CMAKE_C_COMPILER="cc" \
-D CMAKE_CXX_COMPILER="CC" \
-D CMAKE_Fortran_COMPILER="ftn" \
-D Trilinos_CXX11_FLAGS="-std=c++11" \
-D CMAKE_CXX_FLAGS:STRING="$COMPILE_FLAGS" \
-D CMAKE_C_FLAGS:STRING="$COMPILE_FLAGS" \
-D TPL_ENABLE_MPI:BOOL=ON \
-D MPI_EXEC_MAX_NUMPROCS:STRING=4 \
-D CMAKE_BUILD_TYPE=RELEASE \
-D CMAKE_INSTALL_PREFIX:PATH=${INSTALL_DIR} \
-D TPL_ENABLE_BLAS:BOOL=ON \
-D TPL_BLAS_LIBRARIES:FILEPATH="$MKLROOT/lib/intel64/libmkl_intel_thread.a" \
-D TPL_ENABLE_LAPACK:BOOL=ON \
-D TPL_LAPACK_LIBRARIES:FILEPATH="$MKLROOT/lib/intel64/libmkl_intel_thread.a" \
${EXTRA-ARGS} \
${TRILINOS_HOME}

# These work for GNU
# -D TPL_ENABLE_BLAS:BOOL=ON \
# -D TPL_BLAS_LIBRARIES:FILEPATH="$CRAY_LIBSCI_DIR/gnu/61/haswell/lib/libsci_gnu_61_mp.a" \
# -D TPL_ENABLE_LAPACK:BOOL=ON \
# -D TPL_LAPACK_LIBRARIES:FILEPATH="$CRAY_LIBSCI_DIR/gnu/61/haswell/lib/libsci_gnu_61_mp.a" \

# -D Trilinos_ENABLE_INSTALL_CMAKE_CONFIG_FILES:BOOL=ON \
