EXTRA_ARGS=$@

. ./build.inc

TRILINOS_HOME=$TOP/Trilinos

rm CMakeCache.txt
rm -fr CMakeFiles


cmake \
-D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
-D Trilinos_ENABLE_INSTALL_CMAKE_CONFIG_FILES:BOOL=ON \
-D Trilinos_ENABLE_EXAMPLES:BOOL=OFF \
-D Trilinos_ENABLE_TESTS:BOOL=OFF \
-D Trilinos_ENABLE_ALL_PACKAGES:BOOL=OFF \
-D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF \
-D Trilinos_ENABLE_Shards:BOOL=ON \
-D Trilinos_ENABLE_Pamgen:BOOL=ON \
-D Trilinos_ENABLE_Intrepid:BOOL=ON \
-D Trilinos_ENABLE_Teuchos:BOOL=ON \
-D Trilinos_ENABLE_KokkosAlgorithms:BOOL=ON \
-D Trilinos_ENABLE_KokkosCore:BOOL=ON \
-D Trilinos_ENABLE_KokkosContainers:BOOL=ON \
-D Trilinos_ENABLE_KokkosAlgorithms:BOOL=ON \
-D Kokkos_ENABLE_Pthread:BOOL=${BUILD_PTHREADS} \
-D Kokkos_ENABLE_OpenMP:BOOL=${BUILD_OPENMP} \
-D Kokkos_ENABLE_HWLOC:BOOL=OFF \
-D Trilinos_ENABLE_Tpetra:BOOL=ON \
-D Tpetra_ENABLE_Kokkos_Refactor:BOOL=ON \
\
-D Trilinos_ENABLE_SEACAS:BOOL=OFF \
-D Trilinos_ENABLE_SEACASIoss:BOOL=OFF \
-D TPL_ENABLE_Netcdf:BOOL=OFF \
-D TPL_ENABLE_HDF5:BOOL=OFF \
-D Tpetra_INST_COMPLEX_FLOAT:BOOL=OFF \
-D Tpetra_INST_COMPLEX_DOUBLE:BOOL=OFF \
\
-D Teuchos_ENABLE_LONG_LONG_INT:BOOL=OFF \
-D CMAKE_C_COMPILER="$MPIHOME/bin/mpicc" \
-D CMAKE_CXX_COMPILER="$MPIHOME/bin/mpicxx" \
-D CMAKE_Fortran_COMPILER="$MPIHOME/bin/mpif77" \
-D CMAKE_CXX_FLAGS:STRING="$COMPILE_FLAGS" \
-D CMAKE_C_FLAGS:STRING="$COMPILE_FLAGS" \
-D CMAKE_SKIP_RULE_DEPENDENCY=ON \
-D TPL_ENABLE_MPI:BOOL=ON \
-D MPI_BASE_DIR:PATH="$MPIHOME" \
-D MPI_BIN_DIR:FILEPATH="$MPIHOME/bin" \
-D MPI_EXEC_MAX_NUMPROCS:STRING=4 \
-D CMAKE_BUILD_TYPE=${BUILD_FLAG} \
-D CMAKE_INSTALL_PREFIX:PATH=${INSTALL_DIR} \
-D TPL_ENABLE_BLAS:BOOL=ON \
-D TPL_BLAS_LIBRARIES:FILEPATH="/usr/lib64/libblas.so.3" \
-D TPL_ENABLE_LAPACK:BOOL=ON \
-D TPL_LAPACK_LIBRARIES:FILEPATH="/usr/lib64/liblapack.so.3" \
${EXTRA-ARGS} \
${TRILINOS_HOME}

